name: Rebuild Site

on:
  push:
    paths:
      - "src/**"
      - "Makefile"
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: write # Required to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: remove man-db # it makes apt so damn sloooooooowwwwwwwww
      run: sudo apt purge -y man-db

    - name: Install make # --no-install-recommends for not reinstalling man-db
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y make tidy gcc

    - name: Run make
      run: make

    - name: Commit and push changes
      run: |
        git add --all
        git commit -m "[bot] chore: Rebuild site" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"

    - name: Trigger GitHub Pages deployment
      uses: workflow-dispatch@v1
      with:
        workflow: static.yml
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}