name: Rebuild Site

on:
  push:
    paths:
      - "src/**"
      - "Makefile"
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: write # Required to push changes to the repository
  actions: write # Required to trigger other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: remove man-db # it makes apt so damn sloooooooowwwwwwwww
      run: sudo apt purge -y man-db
    - name: Install tools # --no-install-recommends for not reinstalling man-db
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y make tidy gcc
    - name: restore mtime
      uses: chetan/git-restore-mtime-action@v2
      with:
        working-directory: '.'
    - name: Run make
      run: make all
    - name: Commit and push changes
      run: |
        git status -sb
        git add --all
        git status -sb
        git commit -m "chore: Rebuild site" || echo "No changes to commit"
        git push origin HEAD:main || echo "No changes to push"
    - name: Trigger Workflow "static.yml"
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/static.yml/dispatches \
          -d '{"ref":"main"}'
